-- V1: Fresh baseline generated from the current JPA entity model (2026-08-01).
-- Supersedes the old V1 (users/refresh_tokens) + V2 (commerce schema) + V3 (audit
-- columns) migrations, which are gone now that entities are the source of truth
-- during MVP build-out (see docs/CORE_API_DATA_MODEL.md).

BEGIN;

-- ---------------------------------------------------------------------------
-- Shared updated_at trigger
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- Users (staff) & refresh tokens
-- ---------------------------------------------------------------------------

-- Role is a bounded string enum column (see com.angkor.commerce.user.Role) rather than
-- a separate roles/user_roles join table, since each user currently holds one role.
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    username        VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    phone           VARCHAR(30),
    password_hash   VARCHAR(255) NOT NULL,
    image           VARCHAR(500),
    role            VARCHAR(30) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT chk_users_role
        CHECK (role IN ('SUPER_ADMIN', 'SHOP_ADMIN', 'STAFF')),

    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_role ON users (role);

ALTER TABLE users
    ADD CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL;

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Seed a default admin so the system is usable immediately after first migration.
INSERT INTO users (first_name, last_name, username, email, password_hash, role, status)
VALUES ('System', 'Admin', 'admin', 'admin@angkor-commerce.com', '$2a$10$ChSymDNrKZJ.UyTSTOwGu.4hG7FlNhay6VVVOFTAdpzxucCeFOZqi', 'SUPER_ADMIN', 'ACTIVE');

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token_hash  VARCHAR(255) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- Customers (storefront login) & customer refresh tokens
-- ---------------------------------------------------------------------------

-- Self-service login lives directly on customers: every Customer is created through
-- storefront registration, so email/password_hash are always present (no separate
-- customer_accounts table).
CREATE TABLE customers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    company_name    VARCHAR(255),
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    phone           VARCHAR(255),
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    tax_number      VARCHAR(255),
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_customers_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_customers_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT chk_customers_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED')),

    CONSTRAINT chk_customers_identity
        CHECK (
            NULLIF(BTRIM(first_name), '') IS NOT NULL
            OR NULLIF(BTRIM(last_name), '') IS NOT NULL
            OR NULLIF(BTRIM(company_name), '') IS NOT NULL
        )
);

CREATE INDEX idx_customers_name ON customers (last_name, first_name);
CREATE INDEX idx_customers_company_name ON customers (company_name);
CREATE INDEX idx_customers_status ON customers (status);
CREATE UNIQUE INDEX uq_customers_email_lower ON customers (LOWER(email));
CREATE INDEX idx_customers_phone ON customers (phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_customers_tax_number ON customers (tax_number) WHERE tax_number IS NOT NULL;

CREATE TRIGGER trg_customers_set_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN customers.password_hash IS
    'Password hash only; never return this field through API responses.';

CREATE TABLE customer_refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT NOT NULL,
    token_hash      VARCHAR(255) NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    revoked         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_customer_refresh_tokens_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,

    CONSTRAINT uq_customer_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_customer_refresh_tokens_customer_id ON customer_refresh_tokens (customer_id);
CREATE INDEX idx_customer_refresh_tokens_expires_at ON customer_refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- Categories
-- ---------------------------------------------------------------------------

-- Self-referencing tree: top-level rows have parent_id IS NULL; any number of levels.
-- No status/soft-delete column — archive is a hard delete (see CategoryServiceImpl).
CREATE TABLE categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id       BIGINT,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE CASCADE,

    CONSTRAINT fk_categories_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_categories_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT uq_categories_slug UNIQUE (slug),

    CONSTRAINT chk_categories_not_self_parent
        CHECK (parent_id IS DISTINCT FROM id)
);

CREATE INDEX idx_categories_parent_id ON categories (parent_id);

CREATE TRIGGER trg_categories_set_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE categories IS
    'Self-referencing category tree (e.g. Men > T-Shirts, Children > Boys > T-Shirts) shared by every product.';

-- ---------------------------------------------------------------------------
-- Products, variants, images
-- ---------------------------------------------------------------------------

-- Stock/sku deliberately do NOT live here: every product has at least one
-- product_variants row, so variants are the single source of truth for both.
CREATE TABLE products (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                   VARCHAR(200) NOT NULL,
    description             TEXT,
    category_id             BIGINT NOT NULL,

    price                   NUMERIC(19, 4) NOT NULL,
    currency                VARCHAR(3) NOT NULL DEFAULT 'KHR',
    discount_percentage     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    rating                  NUMERIC(3, 2) NOT NULL DEFAULT 0,

    unit                    VARCHAR(50) NOT NULL DEFAULT 'piece',
    thumbnail_url           TEXT,
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_by              BIGINT,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,

    CONSTRAINT fk_products_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT chk_products_price CHECK (price >= 0),
    CONSTRAINT chk_products_discount_percentage CHECK (discount_percentage BETWEEN 0 AND 100),
    CONSTRAINT chk_products_rating CHECK (rating BETWEEN 0 AND 5),
    CONSTRAINT chk_products_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_products_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE INDEX idx_products_title ON products (title);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_status ON products (status);

CREATE TRIGGER trg_products_set_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE products IS
    'Sellable products with DummyJSON-inspired fields such as title, price, thumbnail. Stock/sku live on product_variants, not here.';

-- Every product has at least one row here: real size variants (S/M/L/...) get their
-- own row each, and a product with no size concept gets exactly one row with size = NULL.
CREATE TABLE product_variants (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT NOT NULL,
    size                VARCHAR(50),
    sku                 VARCHAR(100) NOT NULL,
    stock               INTEGER NOT NULL DEFAULT 0,
    price_override      NUMERIC(19, 4),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_variants_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,

    CONSTRAINT chk_product_variants_stock CHECK (stock >= 0),
    CONSTRAINT chk_product_variants_price_override CHECK (price_override IS NULL OR price_override >= 0)
);

CREATE UNIQUE INDEX uq_product_variants_sku ON product_variants (sku);

-- At most one sized row per (product, size)...
CREATE UNIQUE INDEX uq_product_variants_sized
    ON product_variants (product_id, size) WHERE size IS NOT NULL;

-- ...and at most one no-size row per product.
CREATE UNIQUE INDEX uq_product_variants_default
    ON product_variants (product_id) WHERE size IS NULL;

CREATE INDEX idx_product_variants_product_id ON product_variants (product_id);
CREATE INDEX idx_product_variants_low_stock ON product_variants (stock);

CREATE TRIGGER trg_product_variants_set_updated_at
BEFORE UPDATE ON product_variants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE product_variants IS
    'Single source of truth for product stock and sku. size = NULL means the product has no size concept.';

CREATE TABLE product_images (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL,
    image_url       TEXT NOT NULL,
    thumbnail_url   TEXT,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,

    CONSTRAINT uq_product_images_order UNIQUE (product_id, display_order),
    CONSTRAINT chk_product_images_display_order CHECK (display_order >= 0)
);

CREATE INDEX idx_product_images_product_id ON product_images (product_id);

COMMENT ON COLUMN product_images.thumbnail_url IS
    'Small pre-generated preview so grids/listings do not have to download and downscale the full-size image.';

-- ---------------------------------------------------------------------------
-- Orders (storefront checkout — net new, no order_id FK on invoices yet)
-- ---------------------------------------------------------------------------

-- Created only at checkout; cart stays client-only. Shipping address is captured as
-- its own columns (matches customer-portal's ShippingAddress shape), not an FK to
-- a future customer_addresses table.
CREATE TABLE orders (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number            VARCHAR(50) NOT NULL,
    customer_id             BIGINT NOT NULL,

    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    shipping_full_name      VARCHAR(150) NOT NULL,
    shipping_phone          VARCHAR(30) NOT NULL,
    shipping_address        TEXT NOT NULL,
    shipping_city           VARCHAR(100) NOT NULL,
    shipping_postal_code    VARCHAR(30),
    shipping_notes          TEXT,

    subtotal                NUMERIC(19, 4) NOT NULL DEFAULT 0,
    shipping_fee            NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total                   NUMERIC(19, 4) NOT NULL DEFAULT 0,
    currency                VARCHAR(3) NOT NULL DEFAULT 'KHR',

    placed_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,

    CONSTRAINT uq_orders_order_number UNIQUE (order_number),

    CONSTRAINT chk_orders_status CHECK (status IN ('PENDING', 'INVOICED', 'CANCELLED')),
    CONSTRAINT chk_orders_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_orders_non_negative_amounts
        CHECK (subtotal >= 0 AND shipping_fee >= 0 AND total >= 0)
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_placed_at ON orders (placed_at DESC);

CREATE TRIGGER trg_orders_set_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Snapshots title/sku/unit_price_snapshot at order time so later Product price edits
-- never retroactively change a placed order (same pattern as invoice_items below).
-- product_variant_id is never null: every product has >= 1 variant, so checkout never
-- branches on "does this product have variants".
CREATE TABLE order_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT NOT NULL,
    product_id              BIGINT,
    product_variant_id      BIGINT NOT NULL,

    sku                     VARCHAR(100),
    title                   VARCHAR(200) NOT NULL,
    thumbnail_url           TEXT,

    unit_price_snapshot     NUMERIC(19, 4) NOT NULL,
    quantity                INTEGER NOT NULL,
    line_total              NUMERIC(19, 4) NOT NULL,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL,

    CONSTRAINT fk_order_items_product_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants (id) ON DELETE RESTRICT,

    CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_items_unit_price_snapshot CHECK (unit_price_snapshot >= 0),
    CONSTRAINT chk_order_items_line_total CHECK (line_total >= 0)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
CREATE INDEX idx_order_items_product_variant_id ON order_items (product_variant_id);

-- ---------------------------------------------------------------------------
-- Invoices (back-office billing)
-- ---------------------------------------------------------------------------

-- invoice_status is the billing lifecycle; status is the unrelated soft-delete flag
-- shared with other business records (same split as customers/categories/products).
CREATE TABLE invoices (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number          VARCHAR(50) NOT NULL,
    customer_id             BIGINT NOT NULL,

    invoice_status          VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    issue_date              DATE NOT NULL,
    due_date                DATE NOT NULL,

    subtotal                NUMERIC(19, 4) NOT NULL DEFAULT 0,
    discount_percentage     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    discount_amount         NUMERIC(19, 4) NOT NULL DEFAULT 0,
    tax_percentage          NUMERIC(5, 2) NOT NULL DEFAULT 0,
    tax_amount              NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total                   NUMERIC(19, 4) NOT NULL DEFAULT 0,
    paid_amount             NUMERIC(19, 4) NOT NULL DEFAULT 0,
    balance                 NUMERIC(19, 4) NOT NULL DEFAULT 0,

    currency                VARCHAR(3) NOT NULL DEFAULT 'KHR',
    total_items             INTEGER NOT NULL DEFAULT 0,
    total_quantity          INTEGER NOT NULL DEFAULT 0,

    notes                   TEXT,
    issued_at               TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    cancellation_reason     TEXT,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_by              BIGINT,

    CONSTRAINT fk_invoices_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,

    CONSTRAINT fk_invoices_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_invoices_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT uq_invoices_invoice_number UNIQUE (invoice_number),

    CONSTRAINT chk_invoices_invoice_status
        CHECK (invoice_status IN ('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED')),

    CONSTRAINT chk_invoices_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    CONSTRAINT chk_invoices_dates CHECK (due_date >= issue_date),
    CONSTRAINT chk_invoices_discount_percentage CHECK (discount_percentage BETWEEN 0 AND 100),
    CONSTRAINT chk_invoices_tax_percentage CHECK (tax_percentage BETWEEN 0 AND 100),

    CONSTRAINT chk_invoices_non_negative_amounts
        CHECK (
            subtotal >= 0
            AND discount_amount >= 0
            AND tax_amount >= 0
            AND total >= 0
            AND paid_amount >= 0
            AND balance >= 0
        ),

    CONSTRAINT chk_invoices_paid_not_over_total CHECK (paid_amount <= total),
    CONSTRAINT chk_invoices_balance CHECK (balance = total - paid_amount),
    CONSTRAINT chk_invoices_counts CHECK (total_items >= 0 AND total_quantity >= 0),
    CONSTRAINT chk_invoices_currency CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_invoices_cancellation
        CHECK (invoice_status <> 'CANCELLED' OR cancelled_at IS NOT NULL)
);

CREATE INDEX idx_invoices_customer_id ON invoices (customer_id);
CREATE INDEX idx_invoices_invoice_status ON invoices (invoice_status);
CREATE INDEX idx_invoices_issue_date ON invoices (issue_date DESC);
CREATE INDEX idx_invoices_due_date ON invoices (due_date);
CREATE INDEX idx_invoices_created_by ON invoices (created_by);
CREATE INDEX idx_invoices_recent ON invoices (created_at DESC);

CREATE INDEX idx_invoices_outstanding
    ON invoices (due_date, balance)
    WHERE invoice_status IN ('ISSUED', 'PARTIALLY_PAID', 'OVERDUE');

CREATE TRIGGER trg_invoices_set_updated_at
BEFORE UPDATE ON invoices
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Line-item values are snapshots: title/price/sku/thumbnail stay unchanged even when
-- the source product is later edited or removed (product_id nullable, ON DELETE SET NULL).
CREATE TABLE invoice_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id              BIGINT NOT NULL,
    product_id              BIGINT,
    line_number             INTEGER NOT NULL,

    sku                     VARCHAR(100),
    title                   VARCHAR(200) NOT NULL,
    description             TEXT,
    thumbnail_url           TEXT,
    unit                    VARCHAR(50) NOT NULL DEFAULT 'piece',

    price                   NUMERIC(19, 4) NOT NULL,
    quantity                INTEGER NOT NULL,
    total                   NUMERIC(19, 4) NOT NULL,
    discount_percentage     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    discounted_total        NUMERIC(19, 4) NOT NULL,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invoice_items_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,

    CONSTRAINT fk_invoice_items_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL,

    CONSTRAINT uq_invoice_items_line UNIQUE (invoice_id, line_number),

    CONSTRAINT chk_invoice_items_line_number CHECK (line_number > 0),
    CONSTRAINT chk_invoice_items_price CHECK (price >= 0),
    CONSTRAINT chk_invoice_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_invoice_items_total CHECK (total = price * quantity),
    CONSTRAINT chk_invoice_items_discount_percentage CHECK (discount_percentage BETWEEN 0 AND 100),

    CONSTRAINT chk_invoice_items_discounted_total
        CHECK (discounted_total >= 0 AND discounted_total <= total)
);

CREATE INDEX idx_invoice_items_invoice_id ON invoice_items (invoice_id);
CREATE INDEX idx_invoice_items_product_id ON invoice_items (product_id);

CREATE TRIGGER trg_invoice_items_set_updated_at
BEFORE UPDATE ON invoice_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Payments (staff bookkeeping against invoices)
-- ---------------------------------------------------------------------------

-- Not a live payment transaction: no provider tracking, no pending/webhook lifecycle.
-- created_by (inherited) records who recorded the payment.
CREATE TABLE payments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id              BIGINT NOT NULL,

    amount                  NUMERIC(19, 4) NOT NULL,
    currency                VARCHAR(3) NOT NULL DEFAULT 'KHR',
    payment_method          VARCHAR(30) NOT NULL,
    payment_status          VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    payment_date            DATE NOT NULL,

    reference_number        VARCHAR(150),
    notes                   TEXT,

    voided_at               TIMESTAMPTZ,
    void_reason             TEXT,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_by              BIGINT,

    CONSTRAINT fk_payments_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE RESTRICT,

    CONSTRAINT fk_payments_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_payments_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT chk_payments_amount CHECK (amount > 0),
    CONSTRAINT chk_payments_currency CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('CASH', 'BANK_TRANSFER', 'QR_CODE', 'CARD', 'OTHER')),

    CONSTRAINT chk_payments_status
        CHECK (payment_status IN ('COMPLETED', 'VOIDED', 'REFUNDED')),

    CONSTRAINT chk_payments_voided
        CHECK (payment_status <> 'VOIDED' OR voided_at IS NOT NULL)
);

CREATE INDEX idx_payments_invoice_id ON payments (invoice_id);
CREATE INDEX idx_payments_payment_date ON payments (payment_date DESC);
CREATE INDEX idx_payments_payment_method ON payments (payment_method);
CREATE INDEX idx_payments_status ON payments (payment_status);
CREATE UNIQUE INDEX uq_payments_reference_number ON payments (reference_number) WHERE reference_number IS NOT NULL;

CREATE TRIGGER trg_payments_set_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE payments IS
    'Payment transactions recorded against invoices. Invoice paid_amount/balance/invoice_status must be updated in the same application transaction.';

-- ---------------------------------------------------------------------------
-- Audit logs
-- ---------------------------------------------------------------------------

-- Append-only; no write path exists from any module yet.
CREATE TABLE audit_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id       BIGINT,
    action              VARCHAR(100) NOT NULL,
    entity_type         VARCHAR(100) NOT NULL,
    entity_id           VARCHAR(100),
    description         TEXT,

    old_values          JSONB,
    new_values          JSONB,

    ip_address          INET,
    user_agent          TEXT,
    request_id          VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_actor_user_id ON audit_logs (actor_user_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at DESC);
CREATE INDEX idx_audit_logs_old_values_gin ON audit_logs USING GIN (old_values);
CREATE INDEX idx_audit_logs_new_values_gin ON audit_logs USING GIN (new_values);

COMMENT ON TABLE audit_logs IS
    'Append-only history of meaningful business actions and entity changes.';

COMMIT;
