
-- ─────────────────────────────────────────────────────────
-- 1. Link invoices to orders (the baseline never had this)
-- ─────────────────────────────────────────────────────────
BEGIN;
ALTER TABLE invoices ADD COLUMN order_id BIGINT;

ALTER TABLE invoices
    ADD CONSTRAINT fk_invoices_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;

CREATE UNIQUE INDEX uq_invoices_order_id
    ON invoices (order_id) WHERE order_id IS NOT NULL;

CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START 1;

-- ─────────────────────────────────────────────────────────
-- 2. Payment intents
-- ─────────────────────────────────────────────────────────
-- An intent is "we asked the customer to pay". It exists BEFORE any
-- money moves, which is exactly the state your payments table cannot
-- hold: payments requires an invoice_id, and there is no invoice yet.

CREATE TABLE payment_intents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Ours. Sent to PayWay as tran_id, so it must obey PayWay's rules:
    -- max 20 chars. Enforce it here so a bug cannot slip past.
    reference           VARCHAR(20)  NOT NULL,

    order_id            BIGINT       NOT NULL,
    provider            VARCHAR(30)  NOT NULL,   -- ABA_PAYWAY, WALLET, MOCK
    provider_txn_id     VARCHAR(200),            -- PayWay's apv, once approved

    amount              NUMERIC(19,4) NOT NULL,
    currency            VARCHAR(3)    NOT NULL,

    intent_status       VARCHAR(20)  NOT NULL DEFAULT 'CREATED',

    qr_payload          TEXT,                    -- the KHQR string
    deeplink            TEXT,                    -- opens the ABA app

    expires_at          TIMESTAMPTZ,
    confirmed_at        TIMESTAMPTZ,
    failure_reason      TEXT,

    last_polled_at      TIMESTAMPTZ,
    poll_count          INTEGER      NOT NULL DEFAULT 0,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_intents_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT,

    CONSTRAINT uq_payment_intents_reference UNIQUE (reference),

    CONSTRAINT chk_payment_intents_status CHECK (
        intent_status IN ('CREATED','PENDING','SUCCEEDED','FAILED','EXPIRED','CANCELLED')
    ),
    CONSTRAINT chk_payment_intents_amount CHECK (amount > 0),

    -- A succeeded intent must record when and which transaction.
    CONSTRAINT chk_payment_intents_confirmed CHECK (
        intent_status <> 'SUCCEEDED'
        OR (confirmed_at IS NOT NULL AND provider_txn_id IS NOT NULL)
    )
);

CREATE INDEX idx_payment_intents_order  ON payment_intents (order_id);
CREATE INDEX idx_payment_intents_pending
    ON payment_intents (last_polled_at)
    WHERE intent_status IN ('CREATED', 'PENDING');

CREATE TRIGGER trg_payment_intents_set_updated_at
BEFORE UPDATE ON payment_intents
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────────────────────────────────────
-- 3. Raw event log — every pushback, exactly as received
-- ─────────────────────────────────────────────────────────
-- Append-only. When a customer says "I paid but got nothing", this
-- table is how you find out what actually happened.

CREATE TABLE payment_gateway_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider            VARCHAR(30) NOT NULL,
    reference           VARCHAR(50),
    raw_payload         TEXT        NOT NULL,
    remote_ip           VARCHAR(45),
    outcome             VARCHAR(30) NOT NULL,    -- CONFIRMED, IGNORED_DUPLICATE,
                                                 -- VERIFY_FAILED, NOT_FOUND, ERROR
    detail              TEXT,
    received_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_gateway_events_reference ON payment_gateway_events (reference);

-- ─────────────────────────────────────────────────────────
-- 4. Payments: mark where each one came from
-- ─────────────────────────────────────────────────────────

ALTER TABLE payments ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'STAFF';
ALTER TABLE payments ADD COLUMN payment_intent_id BIGINT;

ALTER TABLE payments
    ADD CONSTRAINT chk_payments_source CHECK (source IN ('STAFF', 'GATEWAY'));

ALTER TABLE payments
    ADD CONSTRAINT fk_payments_intent
        FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id)
        ON DELETE SET NULL;

-- THE idempotency backstop: one payment per intent, enforced by the
-- database. Two duplicate confirmations racing each other cannot both
-- insert — one hits this index and fails, and we catch that.
CREATE UNIQUE INDEX uq_payments_intent
    ON payments (payment_intent_id) WHERE payment_intent_id IS NOT NULL;
COMMIT;