-- ─────────────────────────────────────────────────────────
-- Wallets — one per customer, per currency
-- ─────────────────────────────────────────────────────────


BEGIN;
CREATE TABLE customer_wallets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT        NOT NULL,
    currency        VARCHAR(3)    NOT NULL DEFAULT 'USD',

    balance         NUMERIC(19,4) NOT NULL DEFAULT 0,
    status          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',

    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_customer_wallets_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,

    CONSTRAINT uq_customer_wallets_customer_currency
        UNIQUE (customer_id, currency),

    CONSTRAINT chk_customer_wallets_balance CHECK (balance >= 0),
    CONSTRAINT chk_customer_wallets_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_customer_wallets_status
        CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_customer_wallets_customer ON customer_wallets (customer_id);

CREATE TRIGGER trg_customer_wallets_set_updated_at
BEFORE UPDATE ON customer_wallets
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────────────────────────────────────
-- Ledger — append-only. Every balance change lands here.
-- ─────────────────────────────────────────────────────────

CREATE TABLE wallet_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id           BIGINT        NOT NULL,

    txn_type            VARCHAR(20)   NOT NULL,
    direction           VARCHAR(6)    NOT NULL,
    amount              NUMERIC(19,4) NOT NULL,   -- always positive
    balance_after       NUMERIC(19,4) NOT NULL,

    payment_intent_id   BIGINT,
    order_id            BIGINT,
    reference           VARCHAR(100),
    description         TEXT,

    created_by          BIGINT,                   -- null when system-generated
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_wallet_txn_wallet
        FOREIGN KEY (wallet_id) REFERENCES customer_wallets (id) ON DELETE RESTRICT,

    CONSTRAINT fk_wallet_txn_intent
        FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id) ON DELETE SET NULL,

    CONSTRAINT fk_wallet_txn_created_by
        FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT chk_wallet_txn_type CHECK (
        txn_type IN ('TOPUP','PURCHASE','REFUND','ADJUSTMENT','REVERSAL','SEED')
    ),
    CONSTRAINT chk_wallet_txn_direction CHECK (direction IN ('CREDIT','DEBIT')),
    CONSTRAINT chk_wallet_txn_amount CHECK (amount > 0),
    CONSTRAINT chk_wallet_txn_balance_after CHECK (balance_after >= 0)
);

CREATE INDEX idx_wallet_txn_wallet ON wallet_transactions (wallet_id, created_at DESC);
CREATE INDEX idx_wallet_txn_order ON wallet_transactions (order_id);

-- One debit per payment intent. This is the wallet's idempotency AND
-- its "check-transaction": a retried confirm cannot charge twice, and
-- the adapter answers "was this paid?" by looking for this row.
CREATE UNIQUE INDEX uq_wallet_txn_intent
    ON wallet_transactions (payment_intent_id)
    WHERE payment_intent_id IS NOT NULL;

COMMIT;