BEGIN;

CREATE TABLE customer_wishlist_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id  BIGINT       NOT NULL,
    product_id   BIGINT       NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_wishlist_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,

    CONSTRAINT fk_wishlist_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,

    CONSTRAINT uq_wishlist_customer_product UNIQUE (customer_id, product_id)
);

-- The unique constraint indexes (customer_id, product_id) and cannot
-- serve "this customer's list, newest first". This one can.
CREATE INDEX idx_wishlist_customer_created
    ON customer_wishlist_items (customer_id, created_at DESC);

CREATE TRIGGER trg_wishlist_set_updated_at
    BEFORE UPDATE ON customer_wishlist_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
