-- V1: Users and refresh tokens
-- Role is modeled as a bounded string enum (see com.acme.invoice.user.Role) rather than a
-- separate roles/user_roles join table, since each user currently holds exactly one role.
-- Revisit with a proper roles table if multi-role-per-user becomes a requirement.

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(100)        NOT NULL,
    last_name     VARCHAR(100)        NOT NULL,
    username      VARCHAR(100)        NOT NULL,
    email         VARCHAR(255)        NOT NULL,
    phone         VARCHAR(30),
    password_hash VARCHAR(255)        NOT NULL,
    image         VARCHAR(500),
    role          VARCHAR(30)         NOT NULL,
    status        VARCHAR(20)         NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ         NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_by    BIGINT,

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_role ON users (role);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);

-- Seed a default admin so the system is usable immediately after first migration.
-- Password is "ChangeMe123!" hashed with BCrypt (cost 10). CHANGE THIS in any real environment.
INSERT INTO users (first_name, last_name, username, email, password_hash, role, status)
VALUES ('System', 'Admin', 'admin', 'admin@acme.invoice', '$2b$10$SjJIoPvkUkO3VSM807TKwO0CE3O3USM707DFFwcrf0txeAcpWT6/W', 'SUPER_ADMIN', 'ACTIVE');
