-- ACME Invoice Management System
-- PostgreSQL initial database schema
-- Inspired by DummyJSON resource shapes while preserving real invoice-domain rules.
--
-- Target: PostgreSQL 15+
-- Naming: snake_case database columns, camelCase JSON fields in the API.
-- Money: NUMERIC instead of FLOAT/DOUBLE.
-- Time: TIMESTAMPTZ stored in UTC by PostgreSQL/JDBC.
--
-- Dashboard and report modules do not need tables because they aggregate data
-- from customers, products, invoices, invoice_items, and payments.

BEGIN;

-- ---------------------------------------------------------------------------
-- Shared updated_at trigger
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    username            VARCHAR(100) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    phone               VARCHAR(30),
    image_url           TEXT,

    role                VARCHAR(30) NOT NULL DEFAULT 'STAFF',
    record_status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    last_login_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_role
        CHECK (role IN ('SUPER_ADMIN', 'SHOP_ADMIN', 'STAFF', 'VIEWER')),

    CONSTRAINT chk_users_record_status
        CHECK (record_status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

-- Case-insensitive uniqueness without requiring the PostgreSQL CITEXT extension.
CREATE UNIQUE INDEX uq_users_username_lower
    ON users (LOWER(username));

CREATE UNIQUE INDEX uq_users_email_lower
    ON users (LOWER(email));

CREATE INDEX idx_users_role
    ON users (role);

CREATE INDEX idx_users_record_status
    ON users (record_status);

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE users IS
    'Application accounts used for authentication, authorization, ownership, and audit attribution.';

COMMENT ON COLUMN users.password_hash IS
    'Password hash only; never return this field through API responses.';

-- ---------------------------------------------------------------------------
-- Refresh tokens
-- ---------------------------------------------------------------------------

CREATE TABLE refresh_tokens (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    token_hash              VARCHAR(255) NOT NULL,
    expires_at              TIMESTAMPTZ NOT NULL,
    revoked_at              TIMESTAMPTZ,
    replaced_by_token_id    BIGINT,
    created_by_ip           INET,
    revoked_by_ip           INET,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_refresh_tokens_replacement
        FOREIGN KEY (replaced_by_token_id)
        REFERENCES refresh_tokens (id)
        ON DELETE SET NULL,

    CONSTRAINT uq_refresh_tokens_token_hash
        UNIQUE (token_hash),

    CONSTRAINT chk_refresh_tokens_expiration
        CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);

CREATE INDEX idx_refresh_tokens_active
    ON refresh_tokens (user_id, expires_at)
    WHERE revoked_at IS NULL;

COMMENT ON TABLE refresh_tokens IS
    'Hashed refresh tokens used for access-token renewal, rotation, and revocation.';

-- ---------------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------------

CREATE TABLE customers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_type       VARCHAR(20) NOT NULL DEFAULT 'INDIVIDUAL',

    first_name          VARCHAR(100),
    last_name           VARCHAR(100),
    company_name        VARCHAR(200),
    email               VARCHAR(255),
    phone               VARCHAR(30),
    tax_number          VARCHAR(100),

    record_status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by_user_id  BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_customers_created_by
        FOREIGN KEY (created_by_user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_customers_type
        CHECK (customer_type IN ('INDIVIDUAL', 'BUSINESS')),

    CONSTRAINT chk_customers_record_status
        CHECK (record_status IN ('ACTIVE', 'INACTIVE', 'DELETED')),

    CONSTRAINT chk_customers_identity
        CHECK (
            NULLIF(BTRIM(first_name), '') IS NOT NULL
            OR NULLIF(BTRIM(last_name), '') IS NOT NULL
            OR NULLIF(BTRIM(company_name), '') IS NOT NULL
        )
);

CREATE INDEX idx_customers_name
    ON customers (last_name, first_name);

CREATE INDEX idx_customers_company_name
    ON customers (company_name);

CREATE INDEX idx_customers_record_status
    ON customers (record_status);

CREATE INDEX idx_customers_email_lower
    ON customers (LOWER(email))
    WHERE email IS NOT NULL;

CREATE INDEX idx_customers_phone
    ON customers (phone)
    WHERE phone IS NOT NULL;

CREATE UNIQUE INDEX uq_customers_tax_number
    ON customers (tax_number)
    WHERE tax_number IS NOT NULL;

CREATE TRIGGER trg_customers_set_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE customers IS
    'Individuals or businesses that receive invoices.';

-- A separate address table supports DummyJSON-style nested address objects
-- and allows additional billing/shipping addresses later.
CREATE TABLE customer_addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT NOT NULL,
    address_type    VARCHAR(20) NOT NULL DEFAULT 'BILLING',
    address_line    VARCHAR(255) NOT NULL,
    city            VARCHAR(100),
    province        VARCHAR(100),
    postal_code     VARCHAR(30),
    country         VARCHAR(100) NOT NULL DEFAULT 'Cambodia',
    is_primary      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_customer_addresses_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_customer_addresses_type
        CHECK (address_type IN ('BILLING', 'SHIPPING', 'OTHER'))
);

CREATE INDEX idx_customer_addresses_customer_id
    ON customer_addresses (customer_id);

CREATE UNIQUE INDEX uq_customer_primary_address
    ON customer_addresses (customer_id, address_type)
    WHERE is_primary = TRUE;

CREATE TRIGGER trg_customer_addresses_set_updated_at
BEFORE UPDATE ON customer_addresses
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Products
-- ---------------------------------------------------------------------------

CREATE TABLE products (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                   VARCHAR(200) NOT NULL,
    description             TEXT,
    category                VARCHAR(100),

    price                   NUMERIC(19, 4) NOT NULL,
    currency                CHAR(3) NOT NULL DEFAULT 'KHR',
    discount_percentage     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    rating                  NUMERIC(3, 2) NOT NULL DEFAULT 0,
    stock                   INTEGER NOT NULL DEFAULT 0,

    sku                     VARCHAR(100) NOT NULL,
    unit                    VARCHAR(50) NOT NULL DEFAULT 'piece',
    thumbnail_url           TEXT,
    record_status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_by_user_id      BIGINT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_created_by
        FOREIGN KEY (created_by_user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,

    CONSTRAINT uq_products_sku
        UNIQUE (sku),

    CONSTRAINT chk_products_price
        CHECK (price >= 0),

    CONSTRAINT chk_products_discount_percentage
        CHECK (discount_percentage BETWEEN 0 AND 100),

    CONSTRAINT chk_products_rating
        CHECK (rating BETWEEN 0 AND 5),

    CONSTRAINT chk_products_stock
        CHECK (stock >= 0),

    CONSTRAINT chk_products_currency
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_products_record_status
        CHECK (record_status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE INDEX idx_products_title
    ON products (title);

CREATE INDEX idx_products_category
    ON products (category);

CREATE INDEX idx_products_record_status
    ON products (record_status);

CREATE INDEX idx_products_low_stock
    ON products (stock)
    WHERE record_status = 'ACTIVE';

CREATE TRIGGER trg_products_set_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE products IS
    'Sellable products or services exposed with DummyJSON-inspired fields such as title, price, stock, thumbnail, and images.';

CREATE TABLE product_images (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL,
    image_url       TEXT NOT NULL,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_product_images_order
        UNIQUE (product_id, display_order),

    CONSTRAINT chk_product_images_display_order
        CHECK (display_order >= 0)
);

CREATE INDEX idx_product_images_product_id
    ON product_images (product_id);

-- ---------------------------------------------------------------------------
-- Invoices
-- ---------------------------------------------------------------------------

CREATE TABLE invoices (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number          VARCHAR(50) NOT NULL,
    customer_id             BIGINT NOT NULL,

    status                  VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    record_status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    issue_date              DATE NOT NULL,
    due_date                DATE NOT NULL,

    subtotal                NUMERIC(19, 4) NOT NULL DEFAULT 0,
    discount_percentage     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    discount_amount         NUMERIC(19, 4) NOT NULL DEFAULT 0,
    tax_percentage          NUMERIC(5, 2) NOT NULL DEFAULT 0,
    tax_amount              NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total                   NUMERIC(19, 4) NOT NULL DEFAULT 0,
    paid_amount             NUMERIC(19, 4) NOT NULL DEFAULT 0,
    balance                 NUMERIC(19, 4) NOT NULL DEFAULT 0,

    currency                CHAR(3) NOT NULL DEFAULT 'KHR',
    total_items             INTEGER NOT NULL DEFAULT 0,
    total_quantity          INTEGER NOT NULL DEFAULT 0,

    notes                   TEXT,
    issued_at               TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    cancellation_reason     TEXT,

    created_by_user_id      BIGINT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invoices_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_invoices_created_by
        FOREIGN KEY (created_by_user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,

    CONSTRAINT uq_invoices_invoice_number
        UNIQUE (invoice_number),

    CONSTRAINT chk_invoices_status
        CHECK (
            status IN (
                'DRAFT',
                'ISSUED',
                'PARTIALLY_PAID',
                'PAID',
                'OVERDUE',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_invoices_record_status
        CHECK (record_status IN ('ACTIVE', 'INACTIVE', 'DELETED')),

    CONSTRAINT chk_invoices_dates
        CHECK (due_date >= issue_date),

    CONSTRAINT chk_invoices_discount_percentage
        CHECK (discount_percentage BETWEEN 0 AND 100),

    CONSTRAINT chk_invoices_tax_percentage
        CHECK (tax_percentage BETWEEN 0 AND 100),

    CONSTRAINT chk_invoices_non_negative_amounts
        CHECK (
            subtotal >= 0
            AND discount_amount >= 0
            AND tax_amount >= 0
            AND total >= 0
            AND paid_amount >= 0
            AND balance >= 0
        ),

    CONSTRAINT chk_invoices_paid_not_over_total
        CHECK (paid_amount <= total),

    CONSTRAINT chk_invoices_balance
        CHECK (balance = total - paid_amount),

    CONSTRAINT chk_invoices_counts
        CHECK (total_items >= 0 AND total_quantity >= 0),

    CONSTRAINT chk_invoices_currency
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_invoices_cancellation
        CHECK (
            status <> 'CANCELLED'
            OR cancelled_at IS NOT NULL
        )
);

CREATE INDEX idx_invoices_customer_id
    ON invoices (customer_id);

CREATE INDEX idx_invoices_status
    ON invoices (status);

CREATE INDEX idx_invoices_issue_date
    ON invoices (issue_date DESC);

CREATE INDEX idx_invoices_due_date
    ON invoices (due_date);

CREATE INDEX idx_invoices_created_by_user_id
    ON invoices (created_by_user_id);

CREATE INDEX idx_invoices_recent
    ON invoices (created_at DESC);

CREATE INDEX idx_invoices_outstanding
    ON invoices (due_date, balance)
    WHERE status IN ('ISSUED', 'PARTIALLY_PAID', 'OVERDUE');

CREATE TRIGGER trg_invoices_set_updated_at
BEFORE UPDATE ON invoices
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE invoices IS
    'Invoice headers containing customer, lifecycle status, dates, denormalized totals, and payment balance.';

-- Invoice item values are snapshots. Product title, price, SKU, and thumbnail remain
-- unchanged even when the original product is later edited or removed.
CREATE TABLE invoice_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id              BIGINT NOT NULL,
    product_id              BIGINT,
    line_number             INTEGER NOT NULL,

    sku                     VARCHAR(100),
    title                   VARCHAR(200) NOT NULL,
    description             TEXT,
    thumbnail_url           TEXT,
    unit                    VARCHAR(50) NOT NULL DEFAULT 'piece',

    price                   NUMERIC(19, 4) NOT NULL,
    quantity                INTEGER NOT NULL,
    total                   NUMERIC(19, 4) NOT NULL,
    discount_percentage     NUMERIC(5, 2) NOT NULL DEFAULT 0,
    discounted_total        NUMERIC(19, 4) NOT NULL,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invoice_items_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES invoices (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_invoice_items_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE SET NULL,

    CONSTRAINT uq_invoice_items_line
        UNIQUE (invoice_id, line_number),

    CONSTRAINT chk_invoice_items_line_number
        CHECK (line_number > 0),

    CONSTRAINT chk_invoice_items_price
        CHECK (price >= 0),

    CONSTRAINT chk_invoice_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_invoice_items_total
        CHECK (total = price * quantity),

    CONSTRAINT chk_invoice_items_discount_percentage
        CHECK (discount_percentage BETWEEN 0 AND 100),

    CONSTRAINT chk_invoice_items_discounted_total
        CHECK (
            discounted_total >= 0
            AND discounted_total <= total
        )
);

CREATE INDEX idx_invoice_items_invoice_id
    ON invoice_items (invoice_id);

CREATE INDEX idx_invoice_items_product_id
    ON invoice_items (product_id);

CREATE TRIGGER trg_invoice_items_set_updated_at
BEFORE UPDATE ON invoice_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE invoice_items IS
    'Immutable-style invoice line snapshots inspired by DummyJSON cart products.';

-- ---------------------------------------------------------------------------
-- Payments
-- ---------------------------------------------------------------------------

CREATE TABLE payments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id              BIGINT NOT NULL,

    amount                  NUMERIC(19, 4) NOT NULL,
    currency                CHAR(3) NOT NULL DEFAULT 'KHR',
    payment_method          VARCHAR(30) NOT NULL,
    payment_status          VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    payment_date            DATE NOT NULL,

    reference_number        VARCHAR(150),
    notes                   TEXT,
    recorded_by_user_id     BIGINT,

    voided_at               TIMESTAMPTZ,
    void_reason             TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES invoices (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_payments_recorded_by
        FOREIGN KEY (recorded_by_user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_payments_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payments_currency
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_payments_method
        CHECK (
            payment_method IN (
                'CASH',
                'BANK_TRANSFER',
                'QR_CODE',
                'CARD',
                'OTHER'
            )
        ),

    CONSTRAINT chk_payments_status
        CHECK (payment_status IN ('COMPLETED', 'VOIDED', 'REFUNDED')),

    CONSTRAINT chk_payments_voided
        CHECK (
            payment_status <> 'VOIDED'
            OR voided_at IS NOT NULL
        )
);

CREATE INDEX idx_payments_invoice_id
    ON payments (invoice_id);

CREATE INDEX idx_payments_payment_date
    ON payments (payment_date DESC);

CREATE INDEX idx_payments_payment_method
    ON payments (payment_method);

CREATE INDEX idx_payments_status
    ON payments (payment_status);

CREATE UNIQUE INDEX uq_payments_reference_number
    ON payments (reference_number)
    WHERE reference_number IS NOT NULL;

CREATE TRIGGER trg_payments_set_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE payments IS
    'Payment transactions recorded against invoices. Invoice paid_amount, balance, and status must be updated in the same application transaction.';

-- ---------------------------------------------------------------------------
-- Audit logs
-- ---------------------------------------------------------------------------

CREATE TABLE audit_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id       BIGINT,
    action              VARCHAR(100) NOT NULL,
    entity_type         VARCHAR(100) NOT NULL,
    entity_id           VARCHAR(100),
    description         TEXT,

    old_values          JSONB,
    new_values          JSONB,

    ip_address          INET,
    user_agent          TEXT,
    request_id          VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_actor_user_id
    ON audit_logs (actor_user_id);

CREATE INDEX idx_audit_logs_entity
    ON audit_logs (entity_type, entity_id);

CREATE INDEX idx_audit_logs_action
    ON audit_logs (action);

CREATE INDEX idx_audit_logs_created_at
    ON audit_logs (created_at DESC);

CREATE INDEX idx_audit_logs_old_values_gin
    ON audit_logs USING GIN (old_values);

CREATE INDEX idx_audit_logs_new_values_gin
    ON audit_logs USING GIN (new_values);

COMMENT ON TABLE audit_logs IS
    'Append-only history of meaningful business actions and entity changes.';

-- ---------------------------------------------------------------------------
-- Helpful read-only views for dashboard/report modules
-- ---------------------------------------------------------------------------

CREATE VIEW invoice_payment_summary AS
SELECT
    i.id AS invoice_id,
    i.invoice_number,
    i.customer_id,
    i.status,
    i.currency,
    i.total,
    i.paid_amount,
    i.balance,
    COALESCE(
        SUM(p.amount) FILTER (WHERE p.payment_status = 'COMPLETED'),
        0
    ) AS recorded_payment_total,
    COUNT(p.id) FILTER (WHERE p.payment_status = 'COMPLETED') AS payment_count
FROM invoices i
LEFT JOIN payments p
    ON p.invoice_id = i.id
GROUP BY
    i.id,
    i.invoice_number,
    i.customer_id,
    i.status,
    i.currency,
    i.total,
    i.paid_amount,
    i.balance;

CREATE VIEW product_sales_summary AS
SELECT
    ii.product_id,
    ii.title,
    SUM(ii.quantity) AS quantity_sold,
    SUM(ii.discounted_total) AS net_sales
FROM invoice_items ii
JOIN invoices i
    ON i.id = ii.invoice_id
WHERE i.status IN ('ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE')
GROUP BY
    ii.product_id,
    ii.title;

COMMENT ON VIEW invoice_payment_summary IS
    'Reconciliation view comparing stored invoice totals with completed payment rows.';

COMMENT ON VIEW product_sales_summary IS
    'Aggregated product sales used by dashboard and report queries.';

COMMIT;
